# permissions for end users to edit homeagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: homeagent-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prairie-operator
    app.kubernetes.io/part-of: prairie-operator
    app.kubernetes.io/managed-by: kustomize
  name: homeagent-editor-role
rules:
- apiGroups:
  - prairie.kismi
  resources:
  - homeagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prairie.kismi
  resources:
  - homeagents/status
  verbs:
  - get
